const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const root=process.cwd(),ts=require(root+'/node_modules/typescript');
function load(file,mocks){const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,require:n=>n in mocks?mocks[n]:require(n),Buffer,Date,console,fetch:(...args)=>global.fetch(...args),process});return module.exports;}
const access=load('src/lib/guide-access.ts',{'@/lib/totiroom-db':{serviceKey:()=> 'test-secret-only'}});
const u=new URL(access.guideDownloadUrl('lesson'),'https://example.com'),ex=u.searchParams.get('expires'),sig=u.searchParams.get('signature');
assert(access.validGuideAccess('lesson',ex,sig));assert(!access.validGuideAccess('other',ex,sig));assert(!access.validGuideAccess('lesson','1',sig));assert(!access.validGuideAccess('lesson',ex,'x'));
let existing=[],stored=[],guardOk=true,allowed=true;
global.fetch=async(url,opts={})=>{if(opts.method){stored.push(JSON.parse(opts.body));return new Response('',{status:201});}return Response.json(existing)};
const api=load('src/app/api/newsletter/route.ts',{'next/server':{NextResponse:Response},'@/lib/security/form-guard':{guardPublicForm:async()=>({ok:guardOk,message:'captcha'})},'@/lib/security/turnstile':{clientIpFromHeaders:()=> 'test'},'@/lib/security/rate-limit':{withinFormLimits:async()=>allowed,RATE_LIMITED_MESSAGE:'limit'},'@/lib/totiroom-db':{serviceKey:()=> 'test',supabaseUrl:()=> 'https://example.com',restHeaders:()=>({})},'@/lib/video-library':{episodes:[{slug:'lesson'}]},'@/lib/guide-access':access});
async function post(body){return api.POST(new Request('https://example.com',{method:'POST',body:JSON.stringify(body)}))}
(async()=>{let b={name:'Reader',email:'reader@example.com',guide_slug:'lesson',newsletter_consent:true};assert.equal((await post({...b,newsletter_consent:false})).status,400);assert.equal((await post({...b,name:''})).status,400);guardOk=false;assert.equal((await post(b)).status,400);assert.equal(stored.length,0);guardOk=true;allowed=false;assert.equal((await post(b)).status,429);allowed=true;let r=await post(b);assert((await r.json()).download_url);assert.equal(stored[0].name,'Reader');assert(stored[0].source.includes('newsletter-consent-v1'));existing=[{id:'1'}];r=await post({...b,name:'Returning'});assert((await r.json()).download_url);assert.equal(stored[1].name,'Returning');r=await post({email:'plain@example.com'});assert.equal((await r.json()).success,true);console.log('PASS: signed links, tampering/expiry, consent/name validation, bot and rate guards, new/returning subscribers, homepage compatibility');})();
